{% set name = "cool_maps" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rucool/cool_maps/archive/{{ version }}.tar.gz
  sha256: ab30412dd759c35c9624d73267b2c5a24862da9049d4d0330077c6dff623285d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cartopy
    - matplotlib-base
    - cmocean
    - oceans
    - numpy >2.0
    - erddapy

test:
  imports:
    - cool_maps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rucool/cool_maps
  summary: 'Wrapper around Cartopy to easily generate nice-looking maps passing just the extent.'
  license: MIT
  license_file: LICENSE
  doc_url: https://cool_maps.readthedocs.io/

extra:
  recipe-maintainers:
    - najascutellatus
    - lnazzaro
    - lgarzio
